<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;


use Illuminate\Support\Facades\DB;

class PaysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pays')->insert([
            ['nom' => 'Afghanistan', 'code_iso_alpha2' => 'AF', 'code_iso_alpha3' => 'AFG', 'code_iso_num' => 4],
            ['nom' => 'Afrique du Sud', 'code_iso_alpha2' => 'ZA', 'code_iso_alpha3' => 'ZAF', 'code_iso_num' => 710],
            ['nom' => 'Albanie', 'code_iso_alpha2' => 'AL', 'code_iso_alpha3' => 'ALB', 'code_iso_num' => 8],
            ['nom' => 'Algérie', 'code_iso_alpha2' => 'DZ', 'code_iso_alpha3' => 'DZA', 'code_iso_num' => 12],
            ['nom' => 'Allemagne', 'code_iso_alpha2' => 'DE', 'code_iso_alpha3' => 'DEU', 'code_iso_num' => 276],
            ['nom' => 'Andorre', 'code_iso_alpha2' => 'AD', 'code_iso_alpha3' => 'AND', 'code_iso_num' => 20],
            ['nom' => 'Angola', 'code_iso_alpha2' => 'AO', 'code_iso_alpha3' => 'AGO', 'code_iso_num' => 24],
            ['nom' => 'Antigua-et-Barbuda', 'code_iso_alpha2' => 'AG', 'code_iso_alpha3' => 'ATG', 'code_iso_num' => 28],
            ['nom' => 'Arabie Saoudite', 'code_iso_alpha2' => 'SA', 'code_iso_alpha3' => 'SAU', 'code_iso_num' => 682],
            ['nom' => 'Argentine', 'code_iso_alpha2' => 'AR', 'code_iso_alpha3' => 'ARG', 'code_iso_num' => 32],
            ['nom' => 'Arménie', 'code_iso_alpha2' => 'AM', 'code_iso_alpha3' => 'ARM', 'code_iso_num' => 51],
            ['nom' => 'Australie', 'code_iso_alpha2' => 'AU', 'code_iso_alpha3' => 'AUS', 'code_iso_num' => 36],
            ['nom' => 'Autriche', 'code_iso_alpha2' => 'AT', 'code_iso_alpha3' => 'AUT', 'code_iso_num' => 40],
            ['nom' => 'Azerbaïdjan', 'code_iso_alpha2' => 'AZ', 'code_iso_alpha3' => 'AZE', 'code_iso_num' => 31],
            ['nom' => 'Bahamas', 'code_iso_alpha2' => 'BS', 'code_iso_alpha3' => 'BHS', 'code_iso_num' => 44],
            ['nom' => 'Bahreïn', 'code_iso_alpha2' => 'BH', 'code_iso_alpha3' => 'BHR', 'code_iso_num' => 48],
            ['nom' => 'Bangladesh', 'code_iso_alpha2' => 'BD', 'code_iso_alpha3' => 'BGD', 'code_iso_num' => 50],
            ['nom' => 'Barbade', 'code_iso_alpha2' => 'BB', 'code_iso_alpha3' => 'BRB', 'code_iso_num' => 52],
            ['nom' => 'Belgique', 'code_iso_alpha2' => 'BE', 'code_iso_alpha3' => 'BEL', 'code_iso_num' => 56],
            ['nom' => 'Belize', 'code_iso_alpha2' => 'BZ', 'code_iso_alpha3' => 'BLZ', 'code_iso_num' => 84],
            ['nom' => 'Bénin', 'code_iso_alpha2' => 'BJ', 'code_iso_alpha3' => 'BEN', 'code_iso_num' => 204],
            ['nom' => 'Bhoutan', 'code_iso_alpha2' => 'BT', 'code_iso_alpha3' => 'BTN', 'code_iso_num' => 64],
            ['nom' => 'Biélorussie', 'code_iso_alpha2' => 'BY', 'code_iso_alpha3' => 'BLR', 'code_iso_num' => 112],
            ['nom' => 'Birmanie', 'code_iso_alpha2' => 'MM', 'code_iso_alpha3' => 'MMR', 'code_iso_num' => 104],
            ['nom' => 'Bolivie', 'code_iso_alpha2' => 'BO', 'code_iso_alpha3' => 'BOL', 'code_iso_num' => 68],
            ['nom' => 'Bosnie-Herzégovine', 'code_iso_alpha2' => 'BA', 'code_iso_alpha3' => 'BIH', 'code_iso_num' => 70],
            ['nom' => 'Botswana', 'code_iso_alpha2' => 'BW', 'code_iso_alpha3' => 'BWA', 'code_iso_num' => 72],
            ['nom' => 'Brésil', 'code_iso_alpha2' => 'BR', 'code_iso_alpha3' => 'BRA', 'code_iso_num' => 76],
            ['nom' => 'Brunei', 'code_iso_alpha2' => 'BN', 'code_iso_alpha3' => 'BRN', 'code_iso_num' => 96],
            ['nom' => 'Bulgarie', 'code_iso_alpha2' => 'BG', 'code_iso_alpha3' => 'BGR', 'code_iso_num' => 100],
            ['nom' => 'Burkina Faso', 'code_iso_alpha2' => 'BF', 'code_iso_alpha3' => 'BFA', 'code_iso_num' => 854],
            ['nom' => 'Burundi', 'code_iso_alpha2' => 'BI', 'code_iso_alpha3' => 'BDI', 'code_iso_num' => 108],
            ['nom' => 'Cambodge', 'code_iso_alpha2' => 'KH', 'code_iso_alpha3' => 'KHM', 'code_iso_num' => 116],
            ['nom' => 'Cameroun', 'code_iso_alpha2' => 'CM', 'code_iso_alpha3' => 'CMR', 'code_iso_num' => 120],
            ['nom' => 'Canada', 'code_iso_alpha2' => 'CA', 'code_iso_alpha3' => 'CAN', 'code_iso_num' => 124],
            ['nom' => 'Cap-Vert', 'code_iso_alpha2' => 'CV', 'code_iso_alpha3' => 'CPV', 'code_iso_num' => 132],
            ['nom' => 'Chili', 'code_iso_alpha2' => 'CL', 'code_iso_alpha3' => 'CHL', 'code_iso_num' => 152],
            ['nom' => 'Chine', 'code_iso_alpha2' => 'CN', 'code_iso_alpha3' => 'CHN', 'code_iso_num' => 156],
            ['nom' => 'Chypre', 'code_iso_alpha2' => 'CY', 'code_iso_alpha3' => 'CYP', 'code_iso_num' => 196],
            ['nom' => 'Colombie', 'code_iso_alpha2' => 'CO', 'code_iso_alpha3' => 'COL', 'code_iso_num' => 170],
            ['nom' => 'Comores', 'code_iso_alpha2' => 'KM', 'code_iso_alpha3' => 'COM', 'code_iso_num' => 174],
            ['nom' => 'République du Congo', 'code_iso_alpha2' => 'CG', 'code_iso_alpha3' => 'COG', 'code_iso_num' => 178],
            ['nom' => 'République Démocratique du Congo', 'code_iso_alpha2' => 'CD', 'code_iso_alpha3' => 'COD', 'code_iso_num' => 180],
            ['nom' => 'Corée du Nord', 'code_iso_alpha2' => 'KP', 'code_iso_alpha3' => 'PRK', 'code_iso_num' => 408],
            ['nom' => 'Corée du Sud', 'code_iso_alpha2' => 'KR', 'code_iso_alpha3' => 'KOR', 'code_iso_num' => 410],
            ['nom' => 'Costa Rica', 'code_iso_alpha2' => 'CR', 'code_iso_alpha3' => 'CRI', 'code_iso_num' => 188],
            ['nom' => 'Croatie', 'code_iso_alpha2' => 'HR', 'code_iso_alpha3' => 'HRV', 'code_iso_num' => 191],
            ['nom' => 'Cuba', 'code_iso_alpha2' => 'CU', 'code_iso_alpha3' => 'CUB', 'code_iso_num' => 192],
            ['nom' => 'Danemark', 'code_iso_alpha2' => 'DK', 'code_iso_alpha3' => 'DNK', 'code_iso_num' => 208],
            ['nom' => 'Djibouti', 'code_iso_alpha2' => 'DJ', 'code_iso_alpha3' => 'DJI', 'code_iso_num' => 262],
            ['nom' => 'Dominique', 'code_iso_alpha2' => 'DM', 'code_iso_alpha3' => 'DMA', 'code_iso_num' => 212],
            ['nom' => 'Égypte', 'code_iso_alpha2' => 'EG', 'code_iso_alpha3' => 'EGY', 'code_iso_num' => 818],
            ['nom' => 'Émirats arabes unis', 'code_iso_alpha2' => 'AE', 'code_iso_alpha3' => 'ARE', 'code_iso_num' => 784],
            ['nom' => 'Équateur', 'code_iso_alpha2' => 'EC', 'code_iso_alpha3' => 'ECU', 'code_iso_num' => 218],
            ['nom' => 'Érythrée', 'code_iso_alpha2' => 'ER', 'code_iso_alpha3' => 'ERI', 'code_iso_num' => 232],
            ['nom' => 'Espagne', 'code_iso_alpha2' => 'ES', 'code_iso_alpha3' => 'ESP', 'code_iso_num' => 724],
            ['nom' => 'Estonie', 'code_iso_alpha2' => 'EE', 'code_iso_alpha3' => 'EST', 'code_iso_num' => 233],
            ['nom' => 'Eswatini', 'code_iso_alpha2' => 'SZ', 'code_iso_alpha3' => 'SWZ', 'code_iso_num' => 748],
            ['nom' => 'États-Unis', 'code_iso_alpha2' => 'US', 'code_iso_alpha3' => 'USA', 'code_iso_num' => 840],
            ['nom' => 'Éthiopie', 'code_iso_alpha2' => 'ET', 'code_iso_alpha3' => 'ETH', 'code_iso_num' => 231],
            ['nom' => 'Fidji', 'code_iso_alpha2' => 'FJ', 'code_iso_alpha3' => 'FJI', 'code_iso_num' => 242],
            ['nom' => 'Finlande', 'code_iso_alpha2' => 'FI', 'code_iso_alpha3' => 'FIN', 'code_iso_num' => 246],
            ['nom' => 'France', 'code_iso_alpha2' => 'FR', 'code_iso_alpha3' => 'FRA', 'code_iso_num' => 250],
            ['nom' => 'Gabon', 'code_iso_alpha2' => 'GA', 'code_iso_alpha3' => 'GAB', 'code_iso_num' => 266],
            ['nom' => 'Gambie', 'code_iso_alpha2' => 'GM', 'code_iso_alpha3' => 'GMB', 'code_iso_num' => 270],
            ['nom' => 'Géorgie', 'code_iso_alpha2' => 'GE', 'code_iso_alpha3' => 'GEO', 'code_iso_num' => 268],
            ['nom' => 'Ghana', 'code_iso_alpha2' => 'GH', 'code_iso_alpha3' => 'GHA', 'code_iso_num' => 288],
            ['nom' => 'Grèce', 'code_iso_alpha2' => 'GR', 'code_iso_alpha3' => 'GRC', 'code_iso_num' => 300],
            ['nom' => 'Grenade', 'code_iso_alpha2' => 'GD', 'code_iso_alpha3' => 'GRD', 'code_iso_num' => 308],
            ['nom' => 'Guatemala', 'code_iso_alpha2' => 'GT', 'code_iso_alpha3' => 'GTM', 'code_iso_num' => 320],
            ['nom' => 'Guinée', 'code_iso_alpha2' => 'GN', 'code_iso_alpha3' => 'GIN', 'code_iso_num' => 324],
            ['nom' => 'Guinée-Bissau', 'code_iso_alpha2' => 'GW', 'code_iso_alpha3' => 'GNB', 'code_iso_num' => 624],
            ['nom' => 'Guyana', 'code_iso_alpha2' => 'GY', 'code_iso_alpha3' => 'GUY', 'code_iso_num' => 328],
            ['nom' => 'Haïti', 'code_iso_alpha2' => 'HT', 'code_iso_alpha3' => 'HTI', 'code_iso_num' => 332],
            ['nom' => 'Honduras', 'code_iso_alpha2' => 'HN', 'code_iso_alpha3' => 'HND', 'code_iso_num' => 340],
            ['nom' => 'Hongrie', 'code_iso_alpha2' => 'HU', 'code_iso_alpha3' => 'HUN', 'code_iso_num' => 348],
            ['nom' => 'Îles Salomon', 'code_iso_alpha2' => 'SB', 'code_iso_alpha3' => 'SLB', 'code_iso_num' => 90],
            ['nom' => 'Islande', 'code_iso_alpha2' => 'IS', 'code_iso_alpha3' => 'ISL', 'code_iso_num' => 352],
            ['nom' => 'Inde', 'code_iso_alpha2' => 'IN', 'code_iso_alpha3' => 'IND', 'code_iso_num' => 356],
            ['nom' => 'Indonésie', 'code_iso_alpha2' => 'ID', 'code_iso_alpha3' => 'IDN', 'code_iso_num' => 360],
            ['nom' => 'Irak', 'code_iso_alpha2' => 'IQ', 'code_iso_alpha3' => 'IRQ', 'code_iso_num' => 368],
            ['nom' => 'Iran', 'code_iso_alpha2' => 'IR', 'code_iso_alpha3' => 'IRN', 'code_iso_num' => 364],
            ['nom' => 'Irlande', 'code_iso_alpha2' => 'IE', 'code_iso_alpha3' => 'IRL', 'code_iso_num' => 372],
            ['nom' => 'Israël', 'code_iso_alpha2' => 'IL', 'code_iso_alpha3' => 'ISR', 'code_iso_num' => 376],
            ['nom' => 'Italie', 'code_iso_alpha2' => 'IT', 'code_iso_alpha3' => 'ITA', 'code_iso_num' => 380],
            ['nom' => 'Jamaïque', 'code_iso_alpha2' => 'JM', 'code_iso_alpha3' => 'JAM', 'code_iso_num' => 388],
            ['nom' => 'Japon', 'code_iso_alpha2' => 'JP', 'code_iso_alpha3' => 'JPN', 'code_iso_num' => 392],
            ['nom' => 'Jordanie', 'code_iso_alpha2' => 'JO', 'code_iso_alpha3' => 'JOR', 'code_iso_num' => 400],
            ['nom' => 'Kazakhstan', 'code_iso_alpha2' => 'KZ', 'code_iso_alpha3' => 'KAZ', 'code_iso_num' => 398],
            ['nom' => 'Kenya', 'code_iso_alpha2' => 'KE', 'code_iso_alpha3' => 'KEN', 'code_iso_num' => 404],
            ['nom' => 'Kirghizistan', 'code_iso_alpha2' => 'KG', 'code_iso_alpha3' => 'KGZ', 'code_iso_num' => 417],
            ['nom' => 'Kiribati', 'code_iso_alpha2' => 'KI', 'code_iso_alpha3' => 'KIR', 'code_iso_num' => 296],
            ['nom' => 'Koweït', 'code_iso_alpha2' => 'KW', 'code_iso_alpha3' => 'KWT', 'code_iso_num' => 414],
            ['nom' => 'Laos', 'code_iso_alpha2' => 'LA', 'code_iso_alpha3' => 'LAO', 'code_iso_num' => 418],
            ['nom' => 'Lesotho', 'code_iso_alpha2' => 'LS', 'code_iso_alpha3' => 'LSO', 'code_iso_num' => 426],
            ['nom' => 'Lettonie', 'code_iso_alpha2' => 'LV', 'code_iso_alpha3' => 'LVA', 'code_iso_num' => 428],
            ['nom' => 'Liban', 'code_iso_alpha2' => 'LB', 'code_iso_alpha3' => 'LBN', 'code_iso_num' => 422],
            ['nom' => 'Libéria', 'code_iso_alpha2' => 'LR', 'code_iso_alpha3' => 'LBR', 'code_iso_num' => 430],
            ['nom' => 'Libye', 'code_iso_alpha2' => 'LY', 'code_iso_alpha3' => 'LBY', 'code_iso_num' => 434],
            ['nom' => 'Liechtenstein', 'code_iso_alpha2' => 'LI', 'code_iso_alpha3' => 'LIE', 'code_iso_num' => 438],
            ['nom' => 'Lituanie', 'code_iso_alpha2' => 'LT', 'code_iso_alpha3' => 'LTU', 'code_iso_num' => 440],
            ['nom' => 'Luxembourg', 'code_iso_alpha2' => 'LU', 'code_iso_alpha3' => 'LUX', 'code_iso_num' => 442],
            ['nom' => 'Macédoine du Nord', 'code_iso_alpha2' => 'MK', 'code_iso_alpha3' => 'MKD', 'code_iso_num' => 807],
            ['nom' => 'Madagascar', 'code_iso_alpha2' => 'MG', 'code_iso_alpha3' => 'MDG', 'code_iso_num' => 450],
            ['nom' => 'Malaisie', 'code_iso_alpha2' => 'MY', 'code_iso_alpha3' => 'MYS', 'code_iso_num' => 458],
            ['nom' => 'Malawi', 'code_iso_alpha2' => 'MW', 'code_iso_alpha3' => 'MWI', 'code_iso_num' => 454],
            ['nom' => 'Maldives', 'code_iso_alpha2' => 'MV', 'code_iso_alpha3' => 'MDV', 'code_iso_num' => 462],
            ['nom' => 'Mali', 'code_iso_alpha2' => 'ML', 'code_iso_alpha3' => 'MLI', 'code_iso_num' => 466],
            ['nom' => 'Malte', 'code_iso_alpha2' => 'MT', 'code_iso_alpha3' => 'MLT', 'code_iso_num' => 470],
            ['nom' => 'Maroc', 'code_iso_alpha2' => 'MA', 'code_iso_alpha3' => 'MAR', 'code_iso_num' => 504],
            ['nom' => 'Maurice', 'code_iso_alpha2' => 'MU', 'code_iso_alpha3' => 'MUS', 'code_iso_num' => 480],
            ['nom' => 'Mauritanie', 'code_iso_alpha2' => 'MR', 'code_iso_alpha3' => 'MRT', 'code_iso_num' => 478],
            ['nom' => 'Mexique', 'code_iso_alpha2' => 'MX', 'code_iso_alpha3' => 'MEX', 'code_iso_num' => 484],
            ['nom' => 'Micronésie', 'code_iso_alpha2' => 'FM', 'code_iso_alpha3' => 'FSM', 'code_iso_num' => 583],
            ['nom' => 'Moldavie', 'code_iso_alpha2' => 'MD', 'code_iso_alpha3' => 'MDA', 'code_iso_num' => 498],
            ['nom' => 'Monaco', 'code_iso_alpha2' => 'MC', 'code_iso_alpha3' => 'MCO', 'code_iso_num' => 492],
            ['nom' => 'Mongolie', 'code_iso_alpha2' => 'MN', 'code_iso_alpha3' => 'MNG', 'code_iso_num' => 496],
            ['nom' => 'Monténégro', 'code_iso_alpha2' => 'ME', 'code_iso_alpha3' => 'MNE', 'code_iso_num' => 499],
            ['nom' => 'Mozambique', 'code_iso_alpha2' => 'MZ', 'code_iso_alpha3' => 'MOZ', 'code_iso_num' => 508],
            ['nom' => 'Namibie', 'code_iso_alpha2' => 'NA', 'code_iso_alpha3' => 'NAM', 'code_iso_num' => 516],
            ['nom' => 'Nauru', 'code_iso_alpha2' => 'NR', 'code_iso_alpha3' => 'NRU', 'code_iso_num' => 520],
            ['nom' => 'Népal', 'code_iso_alpha2' => 'NP', 'code_iso_alpha3' => 'NPL', 'code_iso_num' => 524],
            ['nom' => 'Nicaragua', 'code_iso_alpha2' => 'NI', 'code_iso_alpha3' => 'NIC', 'code_iso_num' => 558],
            ['nom' => 'Niger', 'code_iso_alpha2' => 'NE', 'code_iso_alpha3' => 'NER', 'code_iso_num' => 562],
            ['nom' => 'Nigéria', 'code_iso_alpha2' => 'NG', 'code_iso_alpha3' => 'NGA', 'code_iso_num' => 566],
            ['nom' => 'Norvège', 'code_iso_alpha2' => 'NO', 'code_iso_alpha3' => 'NOR', 'code_iso_num' => 578],
            ['nom' => 'Nouvelle-Zélande', 'code_iso_alpha2' => 'NZ', 'code_iso_alpha3' => 'NZL', 'code_iso_num' => 554],
            ['nom' => 'Oman', 'code_iso_alpha2' => 'OM', 'code_iso_alpha3' => 'OMN', 'code_iso_num' => 512],
            ['nom' => 'Ouganda', 'code_iso_alpha2' => 'UG', 'code_iso_alpha3' => 'UGA', 'code_iso_num' => 800],
            ['nom' => 'Ouzbékistan', 'code_iso_alpha2' => 'UZ', 'code_iso_alpha3' => 'UZB', 'code_iso_num' => 860],
            ['nom' => 'Pakistan', 'code_iso_alpha2' => 'PK', 'code_iso_alpha3' => 'PAK', 'code_iso_num' => 586],
            ['nom' => 'Palaos', 'code_iso_alpha2' => 'PW', 'code_iso_alpha3' => 'PLW', 'code_iso_num' => 585],
            ['nom' => 'Panama', 'code_iso_alpha2' => 'PA', 'code_iso_alpha3' => 'PAN', 'code_iso_num' => 591],
            ['nom' => 'Papouasie-Nouvelle-Guinée', 'code_iso_alpha2' => 'PG', 'code_iso_alpha3' => 'PNG', 'code_iso_num' => 598],
            ['nom' => 'Paraguay', 'code_iso_alpha2' => 'PY', 'code_iso_alpha3' => 'PRY', 'code_iso_num' => 600],
            ['nom' => 'Pays-Bas', 'code_iso_alpha2' => 'NL', 'code_iso_alpha3' => 'NLD', 'code_iso_num' => 528],
            ['nom' => 'Pérou', 'code_iso_alpha2' => 'PE', 'code_iso_alpha3' => 'PER', 'code_iso_num' => 604],
            ['nom' => 'Philippines', 'code_iso_alpha2' => 'PH', 'code_iso_alpha3' => 'PHL', 'code_iso_num' => 608],
            ['nom' => 'Pologne', 'code_iso_alpha2' => 'PL', 'code_iso_alpha3' => 'POL', 'code_iso_num' => 616],
            ['nom' => 'Portugal', 'code_iso_alpha2' => 'PT', 'code_iso_alpha3' => 'PRT', 'code_iso_num' => 620],
            ['nom' => 'Qatar', 'code_iso_alpha2' => 'QA', 'code_iso_alpha3' => 'QAT', 'code_iso_num' => 634],
            ['nom' => 'République Centrafricaine', 'code_iso_alpha2' => 'CF', 'code_iso_alpha3' => 'CAF', 'code_iso_num' => 140],
            ['nom' => 'République Dominicaine', 'code_iso_alpha2' => 'DO', 'code_iso_alpha3' => 'DOM', 'code_iso_num' => 214],
            ['nom' => 'République Tchèque', 'code_iso_alpha2' => 'CZ', 'code_iso_alpha3' => 'CZE', 'code_iso_num' => 203],
            ['nom' => 'Roumanie', 'code_iso_alpha2' => 'RO', 'code_iso_alpha3' => 'ROU', 'code_iso_num' => 642],
            ['nom' => 'Royaume-Uni', 'code_iso_alpha2' => 'GB', 'code_iso_alpha3' => 'GBR', 'code_iso_num' => 826],
            ['nom' => 'Russie', 'code_iso_alpha2' => 'RU', 'code_iso_alpha3' => 'RUS', 'code_iso_num' => 643],
            ['nom' => 'Rwanda', 'code_iso_alpha2' => 'RW', 'code_iso_alpha3' => 'RWA', 'code_iso_num' => 646],
            ['nom' => 'Saint-Christophe-et-Niévès', 'code_iso_alpha2' => 'KN', 'code_iso_alpha3' => 'KNA', 'code_iso_num' => 659],
            ['nom' => 'Saint-Marin', 'code_iso_alpha2' => 'SM', 'code_iso_alpha3' => 'SMR', 'code_iso_num' => 674],
            ['nom' => 'Saint-Siège (Vatican)', 'code_iso_alpha2' => 'VA', 'code_iso_alpha3' => 'VAT', 'code_iso_num' => 336],
            ['nom' => 'Saint-Vincent-et-les-Grenadines', 'code_iso_alpha2' => 'VC', 'code_iso_alpha3' => 'VCT', 'code_iso_num' => 670],
            ['nom' => 'Sainte-Lucie', 'code_iso_alpha2' => 'LC', 'code_iso_alpha3' => 'LCA', 'code_iso_num' => 662],
            ['nom' => 'Salvador', 'code_iso_alpha2' => 'SV', 'code_iso_alpha3' => 'SLV', 'code_iso_num' => 222],
            ['nom' => 'Samoa', 'code_iso_alpha2' => 'WS', 'code_iso_alpha3' => 'WSM', 'code_iso_num' => 882],
            ['nom' => 'São Tomé-et-Principe', 'code_iso_alpha2' => 'ST', 'code_iso_alpha3' => 'STP', 'code_iso_num' => 678],
            ['nom' => 'Sénégal', 'code_iso_alpha2' => 'SN', 'code_iso_alpha3' => 'SEN', 'code_iso_num' => 686],
            ['nom' => 'Serbie', 'code_iso_alpha2' => 'RS', 'code_iso_alpha3' => 'SRB', 'code_iso_num' => 688],
            ['nom' => 'Seychelles', 'code_iso_alpha2' => 'SC', 'code_iso_alpha3' => 'SYC', 'code_iso_num' => 690],
            ['nom' => 'Sierra Leone', 'code_iso_alpha2' => 'SL', 'code_iso_alpha3' => 'SLE', 'code_iso_num' => 694],
            ['nom' => 'Singapour', 'code_iso_alpha2' => 'SG', 'code_iso_alpha3' => 'SGP', 'code_iso_num' => 702],
            ['nom' => 'Slovaquie', 'code_iso_alpha2' => 'SK', 'code_iso_alpha3' => 'SVK', 'code_iso_num' => 703],
            ['nom' => 'Slovénie', 'code_iso_alpha2' => 'SI', 'code_iso_alpha3' => 'SVN', 'code_iso_num' => 705],
            ['nom' => 'Somalie', 'code_iso_alpha2' => 'SO', 'code_iso_alpha3' => 'SOM', 'code_iso_num' => 706],
            ['nom' => 'Soudan', 'code_iso_alpha2' => 'SD', 'code_iso_alpha3' => 'SDN', 'code_iso_num' => 729],
            ['nom' => 'Soudan du Sud', 'code_iso_alpha2' => 'SS', 'code_iso_alpha3' => 'SSD', 'code_iso_num' => 728],
            ['nom' => 'Sri Lanka', 'code_iso_alpha2' => 'LK', 'code_iso_alpha3' => 'LKA', 'code_iso_num' => 144],
            ['nom' => 'Suède', 'code_iso_alpha2' => 'SE', 'code_iso_alpha3' => 'SWE', 'code_iso_num' => 752],
            ['nom' => 'Suisse', 'code_iso_alpha2' => 'CH', 'code_iso_alpha3' => 'CHE', 'code_iso_num' => 756],
            ['nom' => 'Suriname', 'code_iso_alpha2' => 'SR', 'code_iso_alpha3' => 'SUR', 'code_iso_num' => 740],
            ['nom' => 'Syrie', 'code_iso_alpha2' => 'SY', 'code_iso_alpha3' => 'SYR', 'code_iso_num' => 760],
            ['nom' => 'Tadjikistan', 'code_iso_alpha2' => 'TJ', 'code_iso_alpha3' => 'TJK', 'code_iso_num' => 762],
            ['nom' => 'Tanzanie', 'code_iso_alpha2' => 'TZ', 'code_iso_alpha3' => 'TZA', 'code_iso_num' => 834],
            ['nom' => 'Tchad', 'code_iso_alpha2' => 'TD', 'code_iso_alpha3' => 'TCD', 'code_iso_num' => 148],
            ['nom' => 'Thaïlande', 'code_iso_alpha2' => 'TH', 'code_iso_alpha3' => 'THA', 'code_iso_num' => 764],
            ['nom' => 'Timor-Leste', 'code_iso_alpha2' => 'TL', 'code_iso_alpha3' => 'TLS', 'code_iso_num' => 626],
            ['nom' => 'Togo', 'code_iso_alpha2' => 'TG', 'code_iso_alpha3' => 'TGO', 'code_iso_num' => 768],
            ['nom' => 'Tonga', 'code_iso_alpha2' => 'TO', 'code_iso_alpha3' => 'TON', 'code_iso_num' => 776],
            ['nom' => 'Trinité-et-Tobago', 'code_iso_alpha2' => 'TT', 'code_iso_alpha3' => 'TTO', 'code_iso_num' => 780],
            ['nom' => 'Tunisie', 'code_iso_alpha2' => 'TN', 'code_iso_alpha3' => 'TUN', 'code_iso_num' => 788],
            ['nom' => 'Turkménistan', 'code_iso_alpha2' => 'TM', 'code_iso_alpha3' => 'TKM', 'code_iso_num' => 795],
            ['nom' => 'Turquie', 'code_iso_alpha2' => 'TR', 'code_iso_alpha3' => 'TUR', 'code_iso_num' => 792],
            ['nom' => 'Tuvalu', 'code_iso_alpha2' => 'TV', 'code_iso_alpha3' => 'TUV', 'code_iso_num' => 798],
            ['nom' => 'Ukraine', 'code_iso_alpha2' => 'UA', 'code_iso_alpha3' => 'UKR', 'code_iso_num' => 804],
            ['nom' => 'Uruguay', 'code_iso_alpha2' => 'UY', 'code_iso_alpha3' => 'URY', 'code_iso_num' => 858],
            ['nom' => 'Vanuatu', 'code_iso_alpha2' => 'VU', 'code_iso_alpha3' => 'VUT', 'code_iso_num' => 548],
            ['nom' => 'Venezuela', 'code_iso_alpha2' => 'VE', 'code_iso_alpha3' => 'VEN', 'code_iso_num' => 862],
            ['nom' => 'Viêt Nam', 'code_iso_alpha2' => 'VN', 'code_iso_alpha3' => 'VNM', 'code_iso_num' => 704],
            ['nom' => 'Yémen', 'code_iso_alpha2' => 'YE', 'code_iso_alpha3' => 'YEM', 'code_iso_num' => 887],
            ['nom' => 'Zambie', 'code_iso_alpha2' => 'ZM', 'code_iso_alpha3' => 'ZMB', 'code_iso_num' => 894],
            ['nom' => 'Zimbabwe', 'code_iso_alpha2' => 'ZW', 'code_iso_alpha3' => 'ZWE', 'code_iso_num' => 716],
        ]);
    }
}
